version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - DATABASE_URL=postgres://postgres:revou358067@db.ampdnvtcatrokensnw.supabase.co:5432/postgres
